# Generated by Django 3.0.6 on 2020-05-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0002_race_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='familiar',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='worn_out',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='worn_out',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
